---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
          - id: isort
            args: [--profile=black, --line-length=88]
    - repo: https://github.com/asottile/seed-isort-config
      rev: v2.2.0
      hooks:
          - id: seed-isort-config
    - repo: https://github.com/ambv/black
      rev: 23.10.0
      hooks:
          - id: black
            language_version: python3.10
            args: [--line-length=88]
    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            args: [--max-line-length=88, --extend-ignore=E203]
            exclude: output|data
    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.7.0
      hooks:
          - id: nbqa-black
          - id: nbqa-pyupgrade
            args: [--py36-plus]
          - id: nbqa-isort
            exclude: output|data
          - id: nbqa-flake8
            args: [--max-line-length=88]
    - repo: local
      hooks:
          - id: jupyter-nb-clear-output
            name: jupyter-nb-clear-output
            files: \.ipynb$
            stages: [commit]
            language: system
            # TODO: replace, jupyter 7 does not support plugins, needed to downgrade jupyter poetry add --upgrade notebook==6.4.12
            entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3 # or specific tags
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.6.1
      hooks:
          - id: mypy
            additional_dependencies: [pydantic] # add if use pydantic
    # matches conventional commit messages
    # https://www.conventionalcommits.org/en/v1.0.0/#summary
    # requires pre-commit install --hook-type commit-msg
    - repo: local
      hooks:
          - id: verify-commit-msg
            name: Conventional commit message prefix
            entry: commit-msg.sh
            language: script
            stages: [commit-msg]
